
name: Task
description: New task to be completed
labels: ["task"]
body:
  - type: input
    id: goal
    attributes:
      label: 💡 Цель
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 📝 Подробное описание
      placeholder: Опишите задачу, которую нужно выполнить.
    validations:
      required: true
  - type: textarea
    id: DOD
    attributes:
      label: 🚩 Definition Of Done
      placeholder: Опишите, что должно быть сделано для завершения задачи.
      value: |
        - [ ] Код написан в соответствии с кодстайлом
        - [ ] Написаны базовые тесты
        - [ ] Код проверен и одобрен
    validations:
      required: true
  - type: textarea
    id: Checklist
    attributes:
      label: ⭐️ Checklist
      placeholder: Опишите шаги, которые нужно выполнить для завершения задачи.
    validations:
      required: false



